#!/bin/bash

if [[ ! -z "${ARCH}" ]]; then
  echo "ARCH env variable not set, required"
  exit 1
fi

if [[ ! -d /mnt/deb ]] then 
  echo "deb directory doesn't exist, required" 
  exit 1
fi

for x in $(find /mnt/dist -type f -name "*.xpak"); do 
  cat=$(echo $x | tr '/' ' ' | awk '{print $3}')
  name=$(echo $x | tr '/' ' ' | awk '{print $NF}' | tr '-' ' ' | awk '{print $1}')
  if [[ -d /mnt/deb/$cat/$name ]]; then 
      cd $cat/$name
      qtbz2 -s $x
      tar -xJvf $x.tar.bz2
      rm $x.tar.bz2
      package=$(basename $x .xpak.tar.bz2)
      rm $($basename $x).xpak
      cd ../../
      ln -s $cat/$name $package_$ARCH
      dpkg-deb --build --root-owner-group $package_$ARCH
      rm $package_$ARCH
  fi
done
